server:
  port: 6064
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anand-kumawat/microservice-config
          clone-on-start: true
